# Generated by Django 5.2.17 on 2026-09-09 14:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.programs.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0002_accountsignature_authsession_refreshcredential_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=apps.programs.models.location_id,
                        editable=False,
                        max_length=64,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code", models.CharField(max_length=50, unique=True)),
                ("name", models.CharField(max_length=150)),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="ProgramCounter",
            fields=[
                (
                    "year",
                    models.PositiveSmallIntegerField(primary_key=True, serialize=False),
                ),
                ("value", models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="ProgramType",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=apps.programs.models.type_id,
                        editable=False,
                        max_length=64,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code", models.CharField(max_length=50, unique=True)),
                ("name", models.CharField(max_length=150)),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="WorkflowPolicy",
            fields=[
                (
                    "id",
                    models.PositiveSmallIntegerField(
                        default=1, primary_key=True, serialize=False
                    ),
                ),
                (
                    "within_stage_mode",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("sequential", "Sequential"),
                            ("parallelAll", "Parallel/all"),
                        ],
                        max_length=20,
                    ),
                ),
                ("rejection_ends_submission", models.BooleanField(null=True)),
                ("cancellation_states", models.JSONField(default=list)),
                ("require_signature", models.BooleanField(null=True)),
                ("allow_self_approval", models.BooleanField(null=True)),
                ("require_type_and_cost", models.BooleanField(null=True)),
                ("max_acknowledgers", models.PositiveSmallIntegerField(default=2)),
                ("max_approvers", models.PositiveSmallIntegerField(default=3)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Program",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=apps.programs.models.program_id,
                        editable=False,
                        max_length=64,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("program_number", models.CharField(max_length=64, unique=True)),
                (
                    "program_name",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("period_start", models.DateField(null=True)),
                ("period_end", models.DateField(null=True)),
                (
                    "estimated_cost",
                    models.DecimalField(decimal_places=2, max_digits=16, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "draft"),
                            ("pendingChecker", "pendingChecker"),
                            ("pendingAcknowledgement", "pendingAcknowledgement"),
                            ("pendingApproval", "pendingApproval"),
                            ("approved", "approved"),
                            ("rejected", "rejected"),
                            ("cancelled", "cancelled"),
                        ],
                        default="draft",
                        max_length=24,
                    ),
                ),
                (
                    "current_stage",
                    models.CharField(
                        choices=[
                            ("checker", "Checker"),
                            ("acknowledgement", "Mengetahui"),
                            ("approval", "Menyetujui"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("version", models.PositiveIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("submitted_at", models.DateTimeField(null=True)),
                ("closed_at", models.DateTimeField(null=True)),
                ("cancellation_reason", models.TextField(blank=True)),
                ("snapshot", models.JSONField(default=dict)),
                ("policy_snapshot", models.JSONField(default=dict)),
                ("locations", models.ManyToManyField(to="programs.location")),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="programs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "proposer_signature",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="accounts.accountsignature",
                    ),
                ),
                (
                    "program_type",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="programs.programtype",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Attachment",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=apps.programs.models.attachment_id,
                        editable=False,
                        max_length=64,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("file_name", models.CharField(max_length=255)),
                ("storage_key", models.CharField(max_length=255, unique=True)),
                ("content_type", models.CharField(max_length=150)),
                ("size_bytes", models.PositiveIntegerField()),
                ("sha256", models.CharField(max_length=64)),
                (
                    "scan_status",
                    models.CharField(
                        choices=[
                            ("pending", "pending"),
                            ("clean", "clean"),
                            ("rejected", "rejected"),
                        ],
                        default="pending",
                        max_length=12,
                    ),
                ),
                ("scan_reason", models.CharField(blank=True, max_length=80)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("scanned_at", models.DateTimeField(null=True)),
                ("removed_at", models.DateTimeField(null=True)),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="attachments",
                        to="programs.program",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ReviewerEligibility",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("acknowledgement", "Mengetahui"),
                            ("approval", "Menyetujui"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviewer_eligibilities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="eligible_for",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ReviewTask",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=apps.programs.models.task_id,
                        editable=False,
                        max_length=64,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("reviewer_snapshot", models.JSONField()),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("checker", "Checker"),
                            ("acknowledgement", "Mengetahui"),
                            ("approval", "Menyetujui"),
                        ],
                        max_length=20,
                    ),
                ),
                ("position", models.PositiveSmallIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("waiting", "waiting"),
                            ("ready", "ready"),
                            ("approved", "approved"),
                            ("rejected", "rejected"),
                            ("voided", "voided"),
                        ],
                        default="waiting",
                        max_length=12,
                    ),
                ),
                ("decided_at", models.DateTimeField(null=True)),
                ("note", models.TextField(null=True)),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="review_tasks",
                        to="programs.program",
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="review_tasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "signature",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="accounts.accountsignature",
                    ),
                ),
            ],
            options={
                "ordering": ["position", "id"],
            },
        ),
        migrations.CreateModel(
            name="DraftReviewer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("acknowledgement", "Mengetahui"),
                            ("approval", "Menyetujui"),
                        ],
                        max_length=20,
                    ),
                ),
                ("position", models.PositiveSmallIntegerField()),
                (
                    "reviewer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="draft_reviewers",
                        to="programs.program",
                    ),
                ),
            ],
            options={
                "ordering": ["position", "id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("program", "stage", "position"),
                        name="unique_draft_review_position",
                    ),
                    models.UniqueConstraint(
                        fields=("program", "stage", "reviewer"),
                        name="unique_draft_reviewer",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="program",
            index=models.Index(
                fields=["owner", "created_at", "id"],
                name="programs_pr_owner_i_d94693_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="program",
            index=models.Index(
                fields=["status", "created_at", "id"],
                name="programs_pr_status_2b1bf6_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="program",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("estimated_cost__gte", 0),
                    ("estimated_cost__isnull", True),
                    _connector="OR",
                ),
                name="nonnegative_program_cost",
            ),
        ),
        migrations.AddConstraint(
            model_name="program",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("period_start__isnull", True),
                    ("period_end__isnull", True),
                    ("period_end__gte", models.F("period_start")),
                    _connector="OR",
                ),
                name="ordered_program_dates",
            ),
        ),
        migrations.AddConstraint(
            model_name="reviewereligibility",
            constraint=models.UniqueConstraint(
                fields=("employee", "reviewer", "stage"),
                name="unique_reviewer_eligibility",
            ),
        ),
        migrations.AddIndex(
            model_name="reviewtask",
            index=models.Index(
                fields=["reviewer", "status", "program"],
                name="programs_re_reviewe_34dae1_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="reviewtask",
            constraint=models.UniqueConstraint(
                fields=("program", "stage", "position"),
                name="unique_review_task_position",
            ),
        ),
    ]
