# Generated by Django 5.2.17 on 2026-09-09 14:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.accounts.models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccountSignature",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=apps.accounts.models.signature_id,
                        editable=False,
                        max_length=64,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("storage_key", models.CharField(max_length=255, unique=True)),
                ("sha256", models.CharField(max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="AuthSession",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=apps.accounts.models.session_id,
                        editable=False,
                        max_length=64,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "client_type",
                    models.CharField(
                        choices=[("native", "Native"), ("web", "Web")], max_length=6
                    ),
                ),
                ("access_hash", models.CharField(max_length=64, unique=True)),
                ("access_expires_at", models.DateTimeField()),
                ("refresh_expires_at", models.DateTimeField()),
                ("revoked_at", models.DateTimeField(null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="RefreshCredential",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token_hash", models.CharField(max_length=64, unique=True)),
                ("used_at", models.DateTimeField(null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="UserRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("submitter", "submitter"),
                            ("checker", "checker"),
                            ("acknowledger", "acknowledger"),
                            ("approver", "approver"),
                            ("backofficeAdmin", "backofficeAdmin"),
                        ],
                        max_length=24,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="user",
            name="checker",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="checked_employees",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
