# Generated by Django 5.2.17 on 2026-09-09 14:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_accountsignature_authsession_refreshcredential_and_more"),
        ("programs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="locations",
            field=models.ManyToManyField(
                blank=True, related_name="employees", to="programs.location"
            ),
        ),
        migrations.AddField(
            model_name="accountsignature",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="signature_versions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="signature",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="accounts.accountsignature",
            ),
        ),
        migrations.AddField(
            model_name="authsession",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="api_sessions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="refreshcredential",
            name="session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="refresh_credentials",
                to="accounts.authsession",
            ),
        ),
        migrations.AddField(
            model_name="userrole",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="role_grants",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="userrole",
            constraint=models.UniqueConstraint(
                fields=("user", "role"), name="unique_user_role"
            ),
        ),
    ]
